### ISSUE TITLE
Cannot use XForm field as attribute value

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1554]
If I have a note with a button, I want to be able to set the href using the contact phone number 
Eg. `<a href="tel://${patient_contact_phone}">Call</a>`

This gets converted to:
`<a href="tel://&lt;span class=" or-output"="" data-value=" /assessment_follow_up/patient_contact_phone "><br>            "&gt;Call</a>`

...which of course doesn't work as intended.

It would be good to know if there is a quick fix or a way to get around this in the XForm, otherwise we can schedule this for after the field test.

**Comment by abbyad** [comment]
Bringing this to the current iteration in case we can get to it.

**Comment by alxndrsn** [comment]
Likely the simplest approach to this would be to make an enketo widget which scans notes for spans whose contents look like phone numbers.  Converting these spans to clickable links would then be simple.  Would this be suitable?

**Comment by abbyad** [comment]
Yes, that would work.

**Comment by abbyad** [comment]
This is now also needed for our Standard app, because we'd want a nurse/manager accessing the app on a phone to be able to follow up with a CHW by calling them from a task.

**Comment by alxndrsn** [comment]
Worth testing this on the latest vanilla enketo - I suspect it's a bug there, but may have been fixed.

**Comment by abbyad** [comment]
Still an issue in 4695, but not sure if we are using the latest vanilla Enketo in that build.

**Comment by garethbowen** [comment]
Upgrading to the latest enketo is blocked by https://github.com/medic/medic-webapp/issues/2989

**Comment by sglangevin** [comment]
Should we consider bringing #2989 into the next iteration? Or we can just bump this feature from 2.10 and schedule it into a later release.

**Comment by garethbowen** [comment]
I think we bump it - this release and milestone are full enough...

**Comment by alxndrsn** [comment]
@marc is there an example form for this bug?

**Comment by abbyad** [comment]
Here is a XLSForm showing this issue: [issue-1554.xlsx](https://github.com/medic/medic-webapp/files/860407/issue-1554.xlsx)

![image](https://cloud.githubusercontent.com/assets/789512/24183174/1ced9256-0e9d-11e7-9108-dbaf9839d0a6.png)

And the XForm generated using [pyxform](https://github.com/medic/pyxform):

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Test Issue 1554</h:title>
    <model>
      <instance>
        <issue-1554 delimiter="#" id="issue_1554" prefix="J1!issue_1554!" version="2017-03-22">
          <phone_number>16505551234</phone_number>
          <phone_button/>
          <meta>
            <instanceID/>
          </meta>
        </issue-1554>
      </instance>
      <bind nodeset="/issue-1554/phone_number" type="string"/>
      <bind nodeset="/issue-1554/phone_button" readonly="true()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/issue-1554/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/issue-1554/phone_number">
      <label>Phone number</label>
    </input>
    <input ref="/issue-1554/phone_button">
      <label>&lt;a href=&quot;tel://<output value=" /issue-1554/phone_number "/>&quot;&gt;Call&lt;/a&gt;</label>
    </input>
  </h:body>
</h:html>
```

**Comment by alxndrsn** [comment]
I don't think this is fixable, directly.  Options seem to be:

* introduce our own markup which will be subsituted for tel links and can have `<output>` embedded inside (e.g. `____tel:<output value="/issue-1554/phone_number"/>____`)
* add a new appearance type for e.g. readonly textfields which will turn them into tel links
