### ISSUE TITLE
missing_named_view errors in sentinel

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2231]
I think when we made the audit log changes we forgot one caller.  If you send in a new message to the webapp you'll see this in the sentinel log.  This likely breaks sentinel, I'm not sure yet.

```
2016-04-22T14:09:35.747Z - error: 2016-04-22T14:09:35.747Z - error: error saving changes on doc 11834821503145048dada162666a0038 seq 69644: {"message":"missing_named_view","stack":"Error: missing_named_view
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:200:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)","name":"Error","error":"not_found","reason":"missing_named_view","scope":"couch","statusCode":404,"request":{"method":"POST","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/_design/medic/_view/audit_records_by_doc","qs":{"include_docs":true},"body":"{\"keys\":[[\"11834821503145048dada162666a0038\"]]}"},"headers":{"date":"Fri, 22 Apr 2016 14:09:35 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":404,"uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/_design/medic/_view/audit_records_by_doc"},"errid":"non_200","description":"couch returned 404"}
```

**Comment by mandric** [comment]
Quick attempt at a patch if you have instances suffering from this. 
Apply like: `cd medic-sentinel && patch -p1 < /path/to/2231-patch.txt`
[2231-patch.txt](https://github.com/medic/medic-webapp/files/232016/2231-patch.txt)

**Comment by mandric** [comment]
Would be good to release these fixes together: https://github.com/medic/medic-webapp/issues/2207

**Comment by estellecomment** [comment]
What's the status on this? Does the patch fix it, should you commit it @mandric ?

**Comment by SCdF** [comment]
Pretty sure this has been fixed, with a combination of various commits over the months.

**Comment by mandric** [comment]
We have an instance running 2.8.4 (lg-kenya) where this is still occurring, reopening.

**Comment by garethbowen** [comment]
No idea what this is complaining about - definitely need to get to the bottom of it.

**Comment by sglangevin** [comment]
What is the status of this issue? @mandric @garethbowen

**Comment by garethbowen** [comment]
Ok. In 2.8.x we have [a migration](https://github.com/medic/medic-api/blob/2a9ffbda8c195a390a4a1bbf9a39859c0d34135e/migrations/separate-audit-db.js) to separate audit docs out into a separate audit db for performance reasons. Unfortunately this change was only made in sentinel in the 2.9.x branch as a fix for #2389 . Up until that change the audit library was looking for the `audit_records_by_doc` in the `medic` db instead of the new `medic-audit` db. The two stacktraces are different but I'm confident this is the same error under the hood.

The options we have for fixes are...

1. Backport the fix to 2.8.x, release, update.
2. Use Milan's script which teaches sentinel about the `medic-audit` db.
3. Upgrade affected instances to 2.9.x.
4. Turn off all transitions on affected instances. I don't think any 2.8.x installations get any benefit from running transitions because they're smartphone only instances. To run SMS workflows that require transitions they will have to update to 2.9+ for other reasons.

@mandric Does this make sense to you?

@sglangevin Are you happy to work around affected 2.8.x instances by doing 2, 3, or 4 above, to avoid doing another 2.8.x release?

**Comment by mandric** [comment]
Make sense.  If the instance doesn't need sentinel then disable it like in #4.  Otherwise not sure which upgrade option is best.  Here's the instances affected:

brac-ug.app.medicmobile.org  2.8.5
cic-guatemalav2.dev.medicmobile.org 2.8.3
lg-kenya.app.medicmobile.org 2.8.5
lg-kenya.dev.medicmobile.org 2.8.5
muso-mali.app.medicmobile.org 2.8.3

**Comment by garethbowen** [comment]
- [x] brac-ug.app.medicmobile.org (transitions disabled)
- [ ] cic-guatemalav2.dev.medicmobile.org CONFIRMED
- [ ] lg-kenya.app.medicmobile.org - CONFIRMED
- [ ] lg-kenya.dev.medicmobile.org - CONFIRMED
- [ ] muso-mali.app.medicmobile.org - CONFIRMED

Suggestion - disable all transitions on the four affected instances to work around the issue. This is the config from brac-ug:

```json
    "transitions": {
        "accept_patient_reports": {
            "disable": true
        },
        "conditional_alerts": {
            "disable": true
        },
        "default_responses": {
            "disable": true
        },
        "update_sent_by": {
            "disable": true
        },
        "ohw_counseling": {
            "disable": true
        },
        "ohw_emergency_report": {
            "disable": true
        },
        "ohw_notifications": {
            "disable": true
        },
        "resolve_pending": {
            "disable": true
        },
        "registration": {
            "disable": true
        },
        "twilio_message": {
            "disable": true
        },
        "update_clinics": {
            "disable": true
        },
        "update_notifications": {
            "disable": true
        },
        "update_scheduled_reports": {
            "disable": true
        },
        "update_sent_forms": {
            "disable": true
        }
    }
```

@mandric @abbyad How should we go about getting this change rolled out?

**Comment by mandric** [comment]
@garethbowen I can just apply it to those instances but I'm not sure if they need sentinel.  They should ideally be applied with a tech lead or project lead?  This config should also work to disable all:
```
{
  "transitions": {}
}
```

**Comment by sglangevin** [comment]
@mandric @garethbowen I agree that option #4 is best. We can disable transitions as we do not currently use SMS reports in any of the projects mentioned - they are all using the Android app. For the CIC Guatemala project, I would double-check with @guptasanchay to be sure. I am positive about the others.

@mandric the tech leads are @derickl for LG, @henokgetachew for BRAC and Eugene for Muso Mali. Derick, Henok, Eugene - can you help implement this on your respective instances?

@guptasanchay who is the tech lead for CIC? They can help update the config as needed.

**Comment by mandric** [comment]
Thinking if we get no replies here in the next few days to just make the config change?

**Comment by erwagasore** [comment]
Transtions are now disabled on both Muso Mali `dev.muso.medicmobile.org` and `muso-mali.app.medicmobile.org`

**Comment by derickl** [comment]
Transitions disabled on both `lg-kenya.app` and `lg-kenya.dev`

**Comment by guptasanchay** [comment]
Confirming here that we can disable transitions for cic-guatemalav2.dev.medicmobile.org. 

Will need someone's assistance to make the configuration change.

**Comment by garethbowen** [comment]
@guptasanchay Let me know if I can help...

**Comment by guptasanchay** [comment]
Transitions are disabled for cic-guatemalav2.dev.medicmobile.org.

Thanks for your help @garethbowen!

**Comment by garethbowen** [comment]
Well that's everyone. If it pops up again, disable all transitions (if you can) and try again.

**Comment by garethbowen** [comment]
@mandric I'd changed them in defaults.js due to laziness, so now it's doubly fixed. Thanks!

**Comment by mandric** [comment]
ok I did:
```
curl -H 'content-type:application/json' -X PUT -d@disable-transitions-2.8.json https://admin:secret@host/medic/_design/medic/_rewrite/update_settings/medic
```
The disable-transitions-2.8.json file has the same contents as above.
