### ISSUE TITLE
Send button does not work in Messages tab

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2531]
Clicking the _Send_ button in the _Messages_ tab in 2.x just collapses the compose frame a bit:

1. <img width="836" alt="screen shot 2016-07-21 at 13 52 51" src="https://cloud.githubusercontent.com/assets/191496/17021777/784f87a2-4f4a-11e6-8471-48a4d5ba3d5d.png">

2. click _Send_

3. <img width="804" alt="screen shot 2016-07-21 at 13 52 55" src="https://cloud.githubusercontent.com/assets/191496/17021783/7e72f2c2-4f4a-11e6-940b-cd9e72d62b9c.png">

The message does not appear to be sent, either from checking the UI, or the `api/sms` endpoint.

---

Error seen in console:

<img width="581" alt="screen shot 2016-07-21 at 14 54 11" src="https://cloud.githubusercontent.com/assets/191496/17023306/0080e44c-4f53-11e6-960c-26a63cc5c247.png">

**Comment by SCdF** [comment]
NB: the stacktrace in the bug description is just a warning (it really shouldn't start with Error!): it shouldn't be causing this issue. It should be fixed though (as in, sending messages shouldn't rely on the facility service having cached all person data)

**Comment by alxndrsn** [comment]
@SCdF I think it starts with `Error` so that the stacktrace is included.

**Comment by garethbowen** [comment]
`console.trace()` is a nicer way to do that.

**Comment by alxndrsn** [comment]
Seems to work now; likely fixed in related tickets.

**Comment by SCdF** [comment]
This looks like it's still broken for me? Note that I don't have medic-gateway, but specifically: when I type a message into messages and hit send, I don't see the message appear in the above view.

**Comment by alxndrsn** [comment]
Can't recreate; what state is this meant to be in (`Acceptance Testing` and open?)

**Comment by SCdF** [comment]
Yay it was my environment. Confirmed that this works.

**Comment by abbyad** [comment]
Moving to Ready as it works fine in v2.9
