### ISSUE TITLE
"Failed - Network Error" when exporting Contacts

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2695]
In Chrome.
![screen shot 2016-09-01 at 11 00 03](https://cloud.githubusercontent.com/assets/911434/18161682/4b1495a2-7033-11e6-8f7d-3189f57cbb0e.png)

I can export reports just fine.
No console errors, no API errors.
The file is called `download`, instead of `contacts-<timestamp>.json` when it's working.

I'm suspecting the `getHref(res)`, in `ajaxDownload` module, with `res` = array[998], is too big to run. When I reduce it to array[5] it goes through.

**Comment by SCdF** [comment]
@estellecomment would you say this is the same as #2694 ? As in, this is occurring because you have a very large data set on a feature that otherwise works? I think this should have the same priority as #2694: i.e. not hugely important unless a client is having trouble.

**Comment by estellecomment** [comment]
It's JSON instead of XML, but otherwise yes.

**Comment by SCdF** [comment]
OK cool I dropped it out of the sprint.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by abbyad** [comment]
@estellecomment has this been resolved by https://github.com/medic/medic-webapp/issues/3107 or https://github.com/medic/medic-webapp/issues/3109?

**Comment by estellecomment** [comment]
Nope, still happening. I'm leaving it open, I'm not sure the feature is being used, but it's definitely broken. 

Now I get this api error : 
```
Server error:
 { code: 503,
  message: 
   { Error: connect ECONNREFUSED 127.0.0.1:5985
       at Object.exports._errnoException (util.js:1023:11)
       at exports._exceptionWithHostPort (util.js:1046:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5985 } }
```

**Comment by SCdF** [comment]
@estellecomment port 5985 is lucene. You probably aren't running lucene, and apparently it's required.

**Comment by estellecomment** [comment]
o_O
Thanks for the fact-checking!

With lucene running, the bug is still happening, and error from api is
```
Server error:
 { code: 503, message: { code: 500 } }
```

Database log says 
```
[info] [<0.3011.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.2867.0>] 127.0.0.1 - - GET /medic/ 401
```
(401??) 
With admin user, locally.

**Comment by SCdF** [comment]
@estellecomment I don't want to sound like a magician, but have you tried running it twice?

**Comment by estellecomment** [comment]
https://www.youtube.com/watch?v=nn2FB1P_Mn8

**Comment by estellecomment** [comment]
I just did, also with one eye closed, still happening. Anything specific you're looking for? :)

**Comment by SCdF** [comment]
Just checking. I've found when I setup lucene locally it always fails the first time.

**Comment by vimemo** [comment]
This is still an issue. It has to do with sorting by name.
For some reason, orderBy: 'name', returns the error described before:
Server error:
 { code: 503, message: { code: 500 } }

Removing the sorting/orderBy works.
Do we need an index for lucene to work?
Do we need a different syntax?

**Comment by garethbowen** [comment]
@SCdF Is this related to your CSV export work?

**Comment by SCdF** [comment]
Good catch, yeah! This will be "fixed" by it being reimplemented in #3594 . I'm going to close this as a wontfix, since the Lucene export api will be deprecated in the work I'm doing.
