### ISSUE TITLE
Some labels are not being translated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3418]
On 2.11.0 some translation labels are not showing even though they are on the instance.

![image](https://cloud.githubusercontent.com/assets/789512/25413571/513a9cc6-29f9-11e7-82ea-4f7286036996.png)

**Comment by garethbowen** [comment]
@abbyad Can you link to an example? Anything in the sentinel log?

**Comment by estellecomment** [comment]
Example: https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0ba96f94b93899b06a4136ab5c36fd3e

`messages.generic.registration_not_found` is not being translated, and not printing a console error about `Missing translation`.
(there are other form labels that aren't translated and that are printing that error, I'm ignoring them.)

**Comment by abbyad** [comment]
Others on that page that are not translating despite having translations in instance: `schedule.anc_lmp`, `messages.generic.registration_not_found`, `selection.report.content.raw`

**Comment by estellecomment** [comment]
Node version is v6.9.5, getting `This node version may not be supported`, don't know if it's related yet

**Comment by SCdF** [comment]
@estellecomment the "official" node version we support is 6.10. This is declared because it's what we test for in travis. In terms of there being changes, there aren't any feature changes between 6.9.5 and 6.10 that I'm aware of, see: http://node.green/ . However, I haven't looked at a changelog between those two versions.

Regardless though, I would say it's unlikely they are related.

**Comment by estellecomment** [comment]
**For `messages.generic.registration_not_found` non-translation :**
It seems to be happening only [in the case described in](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0ba96f94b93899b06a4136ab5c39b416) #3401. 
[In normal cases](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0ba96f94b93899b06a4136ab5c39ae98), the translation is fine.
Note that translations for messages are done by sentinel, not the JS code. So makes sense that it's a sentinel problem...
So waiting for #3401 to see if it fixes it.

Checking out the other ones...

**Comment by estellecomment** [comment]
`selection.report.content.raw` is missing in `message-en.properties` that I got from the db on standard.app. I just added it through the UI, that fixed it. @abbyad You probably want to add it in standard package.

**Comment by estellecomment** [comment]
`schedule.anc_lmp` is displaying fine as "ANC Reminders LMP" for me. 
And that seems to be it for translations. 

Setting this as Blocked by #3401, for `messages.generic.registration_not_found`. @abbyad let me know if you see other ones.

**Comment by SCdF** [comment]
@estellecomment why do you think this is blocked by #3401?

**Comment by estellecomment** [comment]
See comment above : it's only happening in that case.
I'm not sure it's causing it, but would like to see what comes out of it before I launch into it...
https://github.com/medic/medic-webapp/issues/3418#issuecomment-297468435

**Comment by estellecomment** [comment]
Solved by #3401 locally. Closing, please reopen if you see it again.

**Comment by SCdF** [comment]
To be clear if people read this in the future: #3401 did not solve anything to do with translations. Instead, the particular situation that caused that code to attempt to add that translation is not being called.

**Comment by abbyad** [comment]
Given https://github.com/medic/medic-webapp/issues/3418#issuecomment-297506028 I wanted to verify if this is still an issue or not. I tested on 2.11.0 a scenario that would legitimately give the `registration_not_found` error, and it seems to translate properly:

![image](https://cloud.githubusercontent.com/assets/789512/25604214/c2eca410-2ecf-11e7-8b56-5a9a27ccfd36.png)

I think we can keep this issue closed, deal with #3401, and open a new translation issue if needed.
