### ISSUE TITLE
Uncaught Exception: write after end error on 2.14.1

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4460]
This happened while trying to upload config using `medic-conf --instance instance.dev` on a test instance (standard-release.dev).

Medic conf fails with the error:
`ERROR Database encountered an unknown error `

The error on the side of API is this:
```
2018-04-23T12:36:51.081Z - error: UNCAUGHT EXCEPTION!
 
2018-04-23T12:36:51.106Z - error: Server error:
 { Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:439:15)
    at prepareResponse (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:161:12)
    at err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:244:13)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:127:5
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  domainEmitter: 
   ServerResponse {
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] },
     _events: { finish: [Function: resOnFinish] },
     _eventsCount: 1,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: true,
     _removedHeader: {},
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: null,
     connection: null,
     _header: 'HTTP/1.1 200 OK\r\nX-Powered-By: Express\r\nX-Accel-Buffering: no\r\nContent-Type: application/json\r\nDate: Mon, 23 Apr 2018 12:36:50 GMT\r\nConnection: close\r\n\r\n',
     _headers: 
      { 'x-powered-by': 'Express',
        'x-accel-buffering': 'no',
        'content-type': 'application/json' },
     _headerNames: 
      { 'x-powered-by': 'X-Powered-By',
        'x-accel-buffering': 'X-Accel-Buffering',
        'content-type': 'Content-Type' },
     _onPendingData: [Function: updateOutgoingData],
     req: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 0,
        httpVersion: '1.0',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '/medic/_changes?timeout=134217728&style=all_docs&feed=longpoll&seq_interval=100&heartbeat=10000&filter=_doc_ids&since=388951&limit=100',
        method: 'POST',
        statusCode: null,
        statusMessage: null,
        client: [Object],
        _consuming: true,
        _dumped: false,
        next: [Function: next],
        baseUrl: '',
        originalUrl: '/medic/_changes?timeout=134217728&style=all_docs&feed=longpoll&seq_interval=100&heartbeat=10000&filter=_doc_ids&since=388951&limit=100',
        _parsedUrl: [Object],
        params: {},
        query: [Object],
        res: [Circular],
        _startAt: [Object],
        _startTime: 2018-04-23T12:36:47.397Z,
        _remoteAddress: '127.0.0.1',
        route: [Object],
        body: [Object],
        _body: true,
        length: undefined,
        read: [Function] },
     locals: {},
     _startAt: undefined,
     _startTime: undefined,
     statusMessage: 'OK',
     statusCode: 200 },
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: false }
 
2018-04-23T12:36:51.109Z - error: UNCAUGHT EXCEPTION!
 
2018-04-23T12:36:51.112Z - error: Server error:
 { Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:256:15)
    at writeJSON (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:13:7)
    at respond (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:22:12)
    at Object.serverError (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:97:7)
    at Domain.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:85:17)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
 
2018-04-23T12:36:51.112Z - error: UNCAUGHT EXCEPTION!
 
2018-04-23T12:36:51.114Z - error: Server error:
 { Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:256:15)
    at writeJSON (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:13:7)
    at respond (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:22:12)
    at Object.serverError (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:97:7)
    at Domain.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:85:17)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```
We used to run into this error consistently with v2.8 when doing replication and a patch released by @SCdF and rolled out in the 2.8.x branch had fixed it.  I had not seen it before while uploading configuration.  This is likely blocking the rolling out of standard v2.14.1 to all instances since the config is getting messed up (Fails at different points, some forms not getting uploaded etc.).

**Comment by abbyad** [comment]
Can we reproduce this error running medic-conf from another AWS instance? That could rule out a bad internet connection.

**Comment by alxndrsn** [comment]
Specifically this is failing a request to `/medic/_changes?timeout=134217728&style=all_docs&feed=longpoll&seq_interval=100&heartbeat=10000&filter=_doc_ids&since=388951&limit=100`.

I think the stacktrace of the original error is:
```
 2017-11-14T17:51:50.097Z - error: Server error:
  { TypeError: Cannot read property 'map' of undefined
     at updateFeeds (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:375:40)
     at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:411:7
     at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/n
     at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/reques
     at emitTwo (events.js:106:13)
     at Request.emit (events.js:191:7)
     at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/
     at emitOne (events.js:96:13)
     at Request.emit (events.js:188:7)
     at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/
   domain:
    Domain {
      domain: null,
      _events: { error: [Function] },
      _eventsCount: 1,
      _maxListeners: undefined,
      members: [] },
   domainThrown: true }
```

**Comment by alxndrsn** [comment]
Looks like it was fixed in https://github.com/medic/medic-webapp/issues/3099; the server does not have this fix.

**Comment by henokgetachew** [comment]
@SCdF release 2.14.2 and I just tested it on standard-release.  The issue still appears to be there.  Here's the log:
```
2018-04-24T08:58:34.233Z - error: UNCAUGHT EXCEPTION!
 
2018-04-24T08:58:34.257Z - error: Server error:
 { Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:439:15)
    at prepareResponse (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:161:12)
    at err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:244:13)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/handlers/changes.js:127:5
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  domainEmitter: 
   ServerResponse {
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] },
     _events: { finish: [Function: resOnFinish] },
     _eventsCount: 1,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: true,
     _removedHeader: {},
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: null,
     connection: null,
     _header: 'HTTP/1.1 200 OK\r\nX-Powered-By: Express\r\nX-Accel-Buffering: no\r\nContent-Type: application/json\r\nDate: Tue, 24 Apr 2018 08:58:27 GMT\r\nConnection: close\r\n\r\n',
     _headers: 
      { 'x-powered-by': 'Express',
        'x-accel-buffering': 'no',
        'content-type': 'application/json' },
     _headerNames: 
      { 'x-powered-by': 'X-Powered-By',
        'x-accel-buffering': 'X-Accel-Buffering',
        'content-type': 'Content-Type' },
     _onPendingData: [Function: updateOutgoingData],
     req: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 0,
        httpVersion: '1.0',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '/medic/_changes?timeout=134217728&style=all_docs&feed=longpoll&seq_interval=100&heartbeat=10000&filter=_doc_ids&since=451314&limit=88',
        method: 'POST',
        statusCode: null,
        statusMessage: null,
        client: [Object],
        _consuming: true,
        _dumped: false,
        next: [Function: next],
        baseUrl: '',
        originalUrl: '/medic/_changes?timeout=134217728&style=all_docs&feed=longpoll&seq_interval=100&heartbeat=10000&filter=_doc_ids&since=451314&limit=88',
        _parsedUrl: [Object],
        params: {},
        query: [Object],
        res: [Circular],
        _startAt: [Object],
        _startTime: 2018-04-24T08:58:16.957Z,
        _remoteAddress: '127.0.0.1',
        route: [Object],
        body: [Object],
        _body: true,
        length: undefined,
        read: [Function] },
     locals: {},
     _startAt: undefined,
     _startTime: undefined,
     statusMessage: 'OK',
     statusCode: 200 },
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: false }
 
2018-04-24T08:58:34.267Z - error: UNCAUGHT EXCEPTION!
 
2018-04-24T08:58:34.269Z - error: Server error:
 { Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:256:15)
    at writeJSON (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:13:7)
    at respond (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:22:12)
    at Object.serverError (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:97:7)
    at Domain.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:85:17)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
 
2018-04-24T08:58:34.271Z - error: UNCAUGHT EXCEPTION!
 
2018-04-24T08:58:34.272Z - error: Server error:
 { Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:256:15)
    at writeJSON (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:13:7)
    at respond (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:22:12)
    at Object.serverError (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server-utils.js:97:7)
    at Domain.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/server.js:85:17)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

**Comment by SCdF** [comment]
@henokgetachew I wasn't the one who made the change, @alxndrsn did. I'll assign this ticket to him.

**Comment by alxndrsn** [comment]
# Observed
```
[feed:3665822082676205] updateFeeds() calling getChanges()…
[feed:3665822082676205] getChanges() bindServerIds().callback setTimeout() calling getChanges()...
[feed:3665822082676205] prepareResponse() feed.res.finished false
[feed:3665822082676205] getChanges() bindServerIds().callback calling feed.res.end()...
[feed:3665822082676205] prepareResponse() feed.res.finished true
[feed:3665822082676205] getChanges() bindServerIds().callback calling feed.res.end()...
```

# Expected

I'm surprised that:

1. two calls to `getChanges()` are being processed for the same feed concurrently
2. `prepareResponse()` would ever be called after the feed's response has been ended

I suspect *2* is a consequence of *1*.

**Comment by garethbowen** [comment]
I've added comments to the `master` PR: https://github.com/medic/medic-webapp/pull/4495

These apply to the other PRs too.

**Comment by sglangevin** [comment]
@alxndrsn this issue has become pretty urgent while you were out. Have you gotten a chance to look at this one now that you are back?
