### ISSUE TITLE
medic-api logs are inconsistently prefixed

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4470]
# Observed

Calls to `console.log()` are _sometimes_ prefixed with timestamp and log level:

```
2018-04-24T17:38:03.746Z - info: TIMED SECTION COMPLETE bindValidatedDocIds().docs_by_replication_key 4013 ms
 TIMED SECTION COMPLETE bindValidatedDocIds().before-callback 4013 ms
 [feed:5480149124257525] prepareResponse() feed.res.finished false

 2018-04-24T17:38:03.747Z - info: [feed:5480149124257525] getChanges() bindServerIds().callback calling feed.res.end()...
 TIMED SECTION COMPLETE getChanges().end 5186 ms

…

 2018-04-24T17:38:04.081Z - info: TIMED SECTION COMPLETE bindValidatedDocIds().docs_by_replication_key 3134 ms
 TIMED SECTION COMPLETE bindValidatedDocIds().before-callback 3134 ms
 [feed:8659737961919713] prepareResponse() feed.res.finished false

 2018-04-24T17:38:04.082Z - info: [feed:8659737961919713] getChanges() bindServerIds().callback calling feed.res.end()...
 TIMED SECTION COMPLETE getChanges().end 4030 ms

…

 2018-04-24T17:38:04.397Z - info: TIMED SECTION COMPLETE bindSubjectIds().before-callback 1249 ms

…

 2018-04-24T17:38:07.685Z - info: TIMED SECTION COMPLETE bindValidatedDocIds().docs_by_replication_key 4473 ms

 2018-04-24T17:38:07.738Z - info: TIMED SECTION COMPLETE bindValidatedDocIds().before-callback 4490 ms
 [feed:3665822082676205] prepareResponse() feed.res.finished true
 [feed:3665822082676205] getChanges() bindServerIds().callback calling feed.res.end()...
 TIMED SECTION COMPLETE getChanges().end 6535 ms
```

# Expected

I'd expect _all_ calls to have this prefix

**Comment by browndav** [comment]
This has been removed in https://github.com/medic/medic-os/pull/32.

**Comment by garethbowen** [comment]
@browndav I think this is unrelated. The script that was removed was about bundling the logs, this is about what gets written to the logs.

**Comment by garethbowen** [comment]
This appears to be fixed in our Docker environment, but now we get two dates for all the request logging, eg:

```
[2018-06-12 04:54:51] ::ffff:10.16.19.40 - - [12/Jun/2018:04:54:51 +0000] "GET / HTTP/1.1" - - "-" "ELB-HealthChecker/2.0"
```

I think this is because we use morgan and it's including the dates by default. We should remove the date logging because it's a waste of disk space not to mention screen real estate.

**Comment by ngaruko** [comment]
Fixed in #4648. Logs now look like ```REQ 452a6de1-af2e-4f12-b10e-7c2893e3bf63 ::1 admin GET /api/info HTTP/1.1
RES 452a6de1-af2e-4f12-b10e-7c2893e3bf63 ::1 admin GET /api/info HTTP/1.1 200 19 0.709 ms```
as per this [comment](https://github.com/medic/medic-webapp/pull/4648#issuecomment-398266672)

**Comment by garethbowen** [comment]
@ngaruko Does it actually look like that? It should have the date at the front, otherwise this issue is not fixed.

**Comment by ngaruko** [comment]
There is a date at the front @garethbowen 
```
[2018-07-10 01:46:48] REQ c115f586-8049-4f27-8b5c-af52700c79cc ::ffff:10.16.19.40 - GET / HTTP/1.1
[2018-07-10 01:46:48] RES c115f586-8049-4f27-8b5c-af52700c79cc ::ffff:10.16.19.40 - GET / HTTP/1.1 302 52 0.710 ms
[2018-07-10 01:46:56] REQ db76749e-80a9-4622-98b9-d43b0eceaf70 ::ffff:10.16.0.108 - GET / HTTP/1.1
```
