### ISSUE TITLE
Remove blank UI elements

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4682]
In `2.16.0-beta.7` we have a lot of unexpected blank lines in Enketo forms for Standard:

## Actual layout
![image](https://user-images.githubusercontent.com/789512/42116335-c42d232a-7bc4-11e8-9663-9f652755d2cb.png)

## Desired layout
![image](https://user-images.githubusercontent.com/789512/42116292-9ed60a4c-7bc4-11e8-82ea-324fef94b123.png)

## Notes
- The XForm converter tool pyxform requires labels for groups
- We remove the label text in medic-conf if it is `NO_LABEL`
- These labels are still taking vertical space, even if they are blank.
- Sample form is [here](https://github.com/medic/medic-webapp/blob/1403c371e5a693618817d21ebc73f49814ede26b/config/standard/forms/contact/district_hospital-create.xml).

Seems as though the ideal solution would be to remove the actual label, and avoid having blank definitions. This would likely be best done in `medic-conf`.

## Current XForm
Currently we have one of the following for every language in the model:
```
          <text id="/data/district_hospital:label">
            <value></value>
          </text>
```

The label is actually blank but in the UI body:

```
    <group appearance="field-list" ref="/data/district_hospital">
      <label ref="jr:itext('/data/district_hospital:label')"/>
      <group ref="/data/district_hospital/contact">
```

## Ideal XForm

Same as before but with no blank definitions in the model, and no empty UI element in the body:
```
    <group appearance="field-list" ref="/data/district_hospital">
      <group ref="/data/district_hospital/contact">

```

**Comment by alxndrsn** [comment]
>The XForm converter tool pyxform requires labels for groups

It seems worth asking the `pyxform` maintainers _why_ this is the case.  It would be likely be trivial to patch `pyxform` to strip empty labels, activated by a command-line switch to maintain backwards compatibility.  But it would be nice if such a change were accepted upstream.

**Comment by alxndrsn** [comment]
This might also be fixed in `medic-conf`.  If so:
1. [ ] add test for current NO_LABEL behaviour
2. [ ] write horrible regex to match and strip the whole of the label area _and related itext group_ (possibly two regexes)

**Comment by alxndrsn** [comment]
N.B. current `NO_LABEL` behaviour is indirectly tested via the `generate-contact-forms` tests.

Fixing this properly should ensure that unnecessary `<itext>` labels are stripped or not created. This would probably best be done at the `pyxform` level - avoiding generating the `<itext>` element and the corresponding `<label>` will be much simpler than trying to strip all of this from the XML.

This also seems like a feature that would be useful to the wider `xlsform` userbase.

**Comment by abbyad** [comment]
I still see the massive white space with the contact edit forms, such as [this one](https://github.com/medic/medic-webapp/blob/master/config/standard/forms/contact/district_hospital-edit.xml).

Tested on standard.dev, using `pyxform-medic==0.9.27`

It appears from some testing that the vertical space remains, even if the translations were removed. When I remove the actual xml when labels don't have text/translations it removes the blank line.

Eg removing the following from the form above:
`<label ref="jr:itext('/data/district_hospital:label')"/>`

From the original post:
>  no blank definitions in the model, and no empty UI element in the body

It appears that the first part is done, but not the second, which still result is blank vertical space.

-----------------
## Header

Some other vertical space difference seems to be due to CSS, where the header is taller in the default non-page style vs the `pages` style (`<h:body class="pages">`).

### Default style - tall header, among other things
![image](https://user-images.githubusercontent.com/789512/45920942-98485e80-be79-11e8-82b0-a418df01ec52.png)

### Pages style - trim header
![image](https://user-images.githubusercontent.com/789512/45920937-7f3fad80-be79-11e8-9a2e-f97951d28810.png)

Fixing the header CSS on it's own may not be high priority, but figured it would be worth noting in case a similar problem was resulting in other vertical space issues throughout the form.

**Comment by vimemo** [comment]
@abbyad / @newtewt,  please try installing this pyxform version:
git+https://github.com/medic/pyxform.git@medic-conf-1.6#egg=pyxform-medic 
[instructions to install](https://github.com/medic/medic-conf)

This pyxform version removes the empty labels and also orders the translation-lang & text-id nodes alphabetically. Thank you.

**Comment by newtewt** [comment]
@vimemo  @abbyad  I'm kinda confused on some things. The expected reports in medic-conf have the fields but they don't exist in the xls. So when xls2xform generates the xml those fields are not there. I have to assume that these were added in a previous version or the tests would have never passed. 

<last_edited_by/>
              <last_edited_by_person_uuid/>
              <last_edited_by_place_uuid/>

```
            <vaccines/>
            <notes/>
            <contact/>
            <geolocation/>
            <meta>
              <created_by/>
              <created_by_person_uuid/>
              <created_by_place_uuid/>
              <last_edited_by/>
              <last_edited_by_person_uuid/>
              <last_edited_by_place_uuid/>
            </meta>
```

Generated form
```
            <vaccines/>
            <notes/>
            <contact/>
            <geolocation/>
            <meta tag="hidden">
              <created_by/>
              <created_by_person_uuid/>
              <created_by_place_uuid/>
            </meta>
          </clinic>
```

**Comment by abbyad** [comment]
Thanks @vimemo, works great!

@newtewt fixing those forms and tests seems to be a separate issue, we can discuss separately to figure out a way forward on that.

**Comment by abbyad** [comment]
The spacing between the header and the first question displays well now that empty labels are not included:

![image](https://user-images.githubusercontent.com/789512/46154516-55083a00-c243-11e8-8e50-5a1ea5dc9d9d.png)

The title still has additional top padding for forms that don't have the `pages` style. I'll open a medic-webapp issue for dealing with that.

I have pushed to standard-release for further AT.

**Comment by ngaruko** [comment]
LGTM.
Tested on `gamma.dev` and `standard-release` instances. 
![image](https://user-images.githubusercontent.com/6979995/51155882-04921680-18de-11e9-887f-c595cd7a64ef.png)
 --
![image](https://user-images.githubusercontent.com/6979995/51155929-32775b00-18de-11e9-8fd2-db27bce9244f.png)
