### ISSUE TITLE
Users without admin permissions can view the configuration area

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4710]
Users that do not have can_configure permissions can access the configure area if they block certain urls. Was able to find this by stopping the loading of a redirect because I noticed the page loads temporarily. In my local dev environment I was able to view the other users setup in my system. May be because of the difference in roles for the user I was logged in as(no permissions at all vs regional manager). I tried to update or change settings but the system errors because of insufficient privilege. 

**Steps to reproduce**:
Log in as a user that cannot view https://alpha.dev.medicmobile.org/medic/_design/medic-admin/_rewrite/#/users  
Paste https://alpha.dev.medicmobile.org/medic/_design/medic-admin/_rewrite/#/users in the address bar. 
Press Go
User is redirected to messages page because they do not have access.
Add https://alpha.dev.medicmobile.org/medic/login as a blocked url in chrome
Paste https://alpha.dev.medicmobile.org/medic/_design/medic-admin/_rewrite/#/users in the address bar. 

**What should happen**:
User is redirected out or everything is disabled.

**What actually happens**:
User sees the configuration page and is able to view different details about configuration. In my local dev environment I was able to view the other users setup in my system. May be because of the difference in roles. 

**Environment**:

- Instance: alpha.dev.medicmobile.org
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version:  3.0.0

Attached a mov file that shows the issue. 
[configure_permissions.zip](https://github.com/medic/medic-webapp/files/2171476/configure_permissions.zip)

**Comment by garethbowen** [comment]
The content of the page shouldn't render until the auth check is complete.

**Comment by vimemo** [comment]
Please retest. This seems to have been fixed by #4711.

**Comment by newtewt** [comment]
This is now blocking users from getting access. Would this be something we want to display the 403 page or is displaying `{"error":"forbidden","reason":"Insufficient privileges"}` sufficient enough?

![screenshot from 2018-11-29 10-52-53](https://user-images.githubusercontent.com/10531066/49234275-bd030a00-f3c5-11e8-92dd-a37036ee1857.png)

**Comment by newtewt** [comment]
Actually this is still an issue. @vimemo  let me know if you'd like to jump on a call and I can show you how to reproduce.

**Comment by garethbowen** [comment]
Merged and backported to `3.3.x`

**Comment by newtewt** [comment]
Getting redirected to error page when trying to access areas I don't have access to.
