### ISSUE TITLE
Convert Export configuration page to Angular

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#776]

**Comment by abbyad** [comment]
Opening the Audit or User Feedback exports don't work in Excel. I get a "file format or file extension is not valid" error.

The extension is `xlsx` instead of `xlsx`, but changing the file extension I still get the same error..

**Comment by garethbowen** [comment]
I've fixed the extension and added a couple of instructions which might help Excel interpret the file. I only have LibreOffice so I can't full test output.

**Comment by abbyad** [comment]
Unfortunately I still get the same error.

@mandric, you got this to work the first time around, right?

**Comment by garethbowen** [comment]
I've changed the extension and mime type - this should solve the issue.

**Comment by abbyad** [comment]
Works well in 0.5.0-alpha.1254, moving to Ready
